### ISSUE TITLE
Unable to change save location for Markdown Document.

### ISSUE THREAD

**Issue by Y0L042** [EdoFro/Freeplane_MarkdownHelper#10]
How do I change the save location after the initial save of the Markdown Document? The only option given is to overwrite the document at the old location, which might not even exist anymore.

**Comment by EdoFro** [comment]
Just delete the link in the Markdown Document node.
You can do that by **selecting the node** and pressing **Ctrl+k**, and deleting the text in the dialog.

Hope it helps
edo

**Comment by Y0L042** [comment]
Thanks! This plugin is a lifesaver.

**Comment by EdoFro** [comment]
new [version ](https://github.com/EdoFro/Freeplane_MarkdownHelper/releases/tag/v0.1.2) gives the user always the option to change save location.
