### ISSUE TITLE
Problem with the option to hide some nodes

### ISSUE THREAD

**Issue by bepolymathe** [EdoFro/Freeplane_MarkdownHelper#18]
Hi @EdoFro 

I noticed a strange behavior with MDH when trying to use the "hideFolded" option... 

[Capture vidéo du 2023-03-12 13-22-03.webm](https://user-images.githubusercontent.com/29939805/224544631-c4977ff0-84af-4fba-928d-501d15e8e769.webm)

Can you reproduce it? 

```
STDOUT: mars 12, 2023 1:10:49 PM org.freeplane.core.util.LogUtils info
INFOS: freeplane_version = 1.11.1; freeplane_xml_version = freeplane 1.11.1
java_version = 17.0.6; os_name = Linux; os_version = 6.1.14-200.fc37.x86_64
```

**Comment by EdoFro** [comment]
Hi @bepolymathe ,
the note in the MDH node is a formula and it gets only recalculate when any of its descendants change its value (text, details or note). To force the note to update you can create a new child node and delete it, or change the order of any of the nodes.
Try those tricks and see if they work for you.

Also, that feature hides the folded node and its descendants, not only its descendants. I thought it that way to hide complete document parts with its title. 
I don't know if it it the best way. Sometimes I wish it only hides the nonvisible nodes.
Another thing that happens is that a title may become a normal text if you fold all their subtitles. Also here I don't know if it is the best solution the way it is implemented currently.

I almost don't use this feature. When I want to hide branches from MDH I use the 'leaf', the 'won't see monkey' or the 'do not enter' icons.

BR

edo

**Comment by EdoFro** [comment]
@bepolymathe,
can I close this issue?
