### ISSUE TITLE
FP 193 13: Markdown Helper addon v6 errors

### ISSUE THREAD

**Issue by Illegit** [EdoFro/Freeplane_MarkdownHelper#6]
In FP 103 13 MDH v6 creates errors when activating lists, nested lists and tasks, instead v5 is working well.
SFPC

**Comment by EdoFro** [comment]
I'm trying to replicate it.
Can you please submit your log.0 file?

**Comment by Illegit** [comment]
![image](https://user-images.githubusercontent.com/62674157/158023757-98dc3cb5-857e-414c-a810-5a52695a0b5a.png)

in this image you see the MDH nodes and the result in the main

![image](https://user-images.githubusercontent.com/62674157/158023793-b03e40f3-9cf4-466c-9d3b-30d756193aa5.png)
 in this image you see the result of the nested task list

With version 5 it is perfect.

**Comment by EdoFro** [comment]
I uploaded the version I am using. It has some new features, but I haven't update the documentation.

https://github.com/EdoFro/Freeplane_MarkdownHelper/releases/tag/v0.1.1

**Comment by Illegit** [comment]
Thankyou Edo, working well.
SFPC
